-- This Script is Part of the Prometheus Obfuscator by Levno_710
--
-- config.lua
--
-- In this Script, some Global config Variables are defined

local NAME = "Panda Obfuscator";
local REVISION = "";
local VERSION = "v1.3";
local BY = "Panda-Pelican Development LLC";

for _, currArg in pairs(arg) do
	if currArg == "--CI" then
		local releaseName = string.gsub(string.format("%s %s %s", NAME, REVISION, VERSION), "%s", "-")
		print(releaseName)
	end

	if currArg == "--FullVersion" then
		print(VERSION)
	end
end

-- Config Starts here
return {
	Name = NAME,
	NameUpper = string.upper(NAME),
	NameAndVersion = string.format("%s %s", NAME, VERSION),
	Version = VERSION;
	Revision = REVISION;
	-- Config Starts Here
	IdentPrefix = "__panda_"; -- Prefix used for identifiers generated by Panda Obfuscator. No identifier in the input script may start with this prefix.

	SPACE = " "; -- The Whitespace to be used by the unparser
	TAB = "\t"; -- The Tab Whitespace to be used by the unparser for pretty printing
}